### ISSUE TITLE
7.1a - As developers creating test for our application it would benefit us if we had a separate database for testing with our own data.

### ISSUE THREAD

**Issue by MrPrip** [ITU-BDSA23-GROUP2/Chirp#36]
It is easier to test if you know what data is in the database and it dosen't change whenever a new user sends a Cheep. It would therefore help if we had a separate testing database we could use, with our own data. Furthermore it would be best if we made and kept it in-memory.

Acceptance criteria:
- When we use am in-memory database for our integration tests.

**Comment by cpilITU** [comment]
Added In Memory Tests on the branch TrueInMemoryTests. Unit tests are still currently failing. Will try to make pull request to main tomorrow.
